In [133]:
import xlwings as xw
import pandas as pd
data1 = pd.read_excel("C:\\Users\\Dmitrii\\Downloads\\10-8.xlsx")
klad = pd.read_excel("C:\\Users\Dmitrii\\Downloads\\Сводный табель АБ №10-8 МАРТ 2021.xlsx")
data1 = data1.drop([0, 1, 2, 3, 4, 5, 6]) #удалить первых 7 строк
data1 = data1.drop(['Unnamed: 6', 'Unnamed: 7'], axis = 1) # удаляемем ненужные колонки
klad = klad.drop([0])
klad.drop(klad.columns.difference(['Unnamed: 1', 'Unnamed: 21']), 1, inplace=True) # удаляем все кроме нужных столбцов

In [134]:
data1.columns = ['Unnamed: 1', 'a', 'b', 'c', 'd', 'e']
klad.columns = ['Unnamed: 1', 'Unnamed: 21']

In [135]:
result = data1.merge(klad, how = 'left', left_on='Unnamed: 1', right_on='Unnamed: 1')

In [137]:
result

,Unnamed: 1,a,b,c,d,e,Unnamed: 21
0,АД-100 [109238],18.03.2021 03:32:12,18.03.2021 03:35:42,Основная,Заправка,25.4,NaN
1,Урал [р 006 ах 163],18.03.2021 04:44:52,18.03.2021 04:51:22,Основная,Заправка,100.3,NaN
2,Denyo DCW [109523],18.03.2021 05:15:20,18.03.2021 05:19:20,Основная,Заправка,23.6,NaN
3,ГАЗ [с 086 вв 163],18.03.2021 06:20:11,18.03.2021 06:23:41,Основная,Заправка,37.8,NaN
4,ППУА Урал [а 923 тс 763],18.03.2021 06:21:57,18.03.2021 06:29:57,Основная,Заправка,97,NaN
...,...,...,...,...,...,...,...
58,Denyo DCW [109523],18.03.2021 20:57:20,18.03.2021 21:01:50,Основная,Заправка,21.4,NaN
59,ГАЗ [с 086 вв 163],18.03.2021 20:57:42,18.03.2021 21:01:42,Основная,Заправка,42.5,NaN
60,Shindaiwa [112154],18.03.2021 21:21:41,18.03.2021 21:26:11,Основная,Заправка,19.4,NaN
61,W.Neuson LTN8L [112455],18.03.2021 21:23:31,18.03.2021 21:29:01,Основная,Заправка,27.9,NaN
62,W.Neuson LTN8L [112456],18.03.2021 21:29:58,18.03.2021 21:35:28,Основная,Заправка,29.3,NaN

In [136]:
result.to_excel("value1.xlsx")

In [ ]:
# TO DO сделать для УМ
# Сделать отдельную таблицу для техники де будет сопоставление названий техники кладовщика с названием техники из Omnicomm